''' this program is like short term memory for ai
with this it stores user before prompts / request and process that 
if future prompt request interaction with the past prompt object '''

# import all dependiences
import json
from pathlib import Path
from voice_input.Keys.config import memory_path

# locating memory folder for ai
memory_path = memory_path

''' Improved script saver: Now it can track sequence of prompts '''

# script saver in json format
# this function stores the prompt which is used to make 3d object
def script_saver(script_name, script_content, user_prompt, parameters = {"key":"value"}):
    # 1st principle ensure that directory exists
    memory_path.parent.mkdir(parents=True, exist_ok= True)
    
    # 2nd principle type sheielding preveing loop crash "Not a string"
    # this condition is going to convert set {} into string()
    if isinstance(script_content, set):
        # FIX: was list(script_name) — should be list(script_content)
        script_content = list(script_content)[0]

    clean_name = str(script_name)
    clean_parameters = parameters if isinstance(parameters,dict) else {}

    #loading memory (history_info)
    previous_conv = []
    if memory_path.exists() and memory_path.stat().st_size >0:
        try:
            with open(memory_path, "r") as file:
                old_info = json.load(file)  
                previous_conv = old_info.get("history",[])
        except:
            previous_conv = []
    
    # this add new prompt / interaction with ai to info list
    new_prompt = {
        "prompt": user_prompt, 
        "code_segment":script_content
    }
    previous_conv.append(new_prompt)
    
    # this stores current use script details so ai can modify it
    store_data = {
        "current_file":script_name,
        "code":script_content, # a complete script generated by ai
        "history":previous_conv, # previous prompts and code
        "parameters":parameters if isinstance(parameters, dict) else {}
    }

    # saving the memory
    with open(memory_path, "w") as file:
        json.dump(store_data, file , indent=4)
    print(f"[Memory] Saved → {memory_path}")
    print("[Memory] Updated successfully.")

''' improved memory loader '''

# load the memory to ai
def load_memory():
    ''' this retrives the last known script from the memory '''
    try:
        # check if memory path exitts
        if not memory_path.exists():
            print("memory path isn't exists yet")
            return None
    except Exception as e:
        # FIX: missing f-prefix meant {e} printed literally
        print(f"Memory is either empty or corrupted:\n{e}")
        return None

    # checking file is empthy before reading
    if memory_path.read_text().strip() == "":
        print("Memory is empty")
        return None

    # after check of memory isn't empty load it
    with open(memory_path,"r") as file:
        # load memory
        return json.load(file)

''' improved get_memory for ai '''
# getting last memory for ai to read and process futher
def get_memory():
    ''' a quick helper to get last memory for ai to read '''
    last_memory = load_memory()

    '''definig the memory of ai context and its project state'''
    # checking for last memory info
    if not last_memory:
        return "Context: No Context Found"
    
    history_info = "\n".join([f"-User Said: {h_info['prompt']}"for h_info in last_memory.get("history",[])])
    info =(
        f"Context of previous Step: \n{history_info}\n\n"
        f"Existing source code: \n{last_memory.get('code')}\n\n"
        f"Instruction: Use the Variable defned above to modify the tool"
    )


    return info
