''' runner.py is like phone case if phone falls case protects phone , just like that if any error occurs
runner.py tries to fix if not it stores the cause of error for later fixex '''

# importing nessary modules
import subprocess
import os
from pathlib import Path
import sys

# adding progresion bar
from tqdm import tqdm
import time

# 1. Setup Folder Paths
# import all folder path from config file
from voice_input.Keys.config import output_location, script_location, logs_location, free_cad_cmd, ai_gen_script, ai_gen_folder

# 2. the checker (make sure that output and logs folder exists)
mandatory_path = [output_location, logs_location]
for folder in mandatory_path:
    if not folder.exists():
        print(f"Creating Folder:", {folder})
        folder.mkdir(parents = True, exist_ok = True)

# a defense mechanisim for not creating an invalid code by ai
import ast

# creating a defensive mechanism
def defense_wall(script_path):
    # reading the generated script
    with open(script_path, "r") as file:
        code = file.read()
        # checking for syntax error
        try:
            # if syntax is correct it returns True
            ast.parse(code)
            return True
        except SyntaxError as e:
            # if syntax is wrong it returns False
            print(f"Syntax Error is generated by script:{e}")
            return False

# 3. the executor (runns all the function)
def execute_cad_scripts(script_name):
    # mentioning script path
    script_path_use = ai_gen_folder / script_name
    print(f"Running Script:",(script_name))
    # we define this so every part of code can access / see this
    log_report = logs_location / "error.report.txt"

    # calling defensive wall to check the code
    if not defense_wall(script_path_use):
        print("Script is invalid")
        # entering log
        with open(log_report, "a")as file:
            file.write(f"Syntax_Error in {script_name}\n")
        return False

    # initializing bar format
    bar_format = "|{bar}| {percentage:3.0f}% {n_fmt}/{total_fmt} [{elapsed}<{remaining}]"

    # mentioning stages
    stages = [
        ("Location"),
        ("Defense Wall"),
        ("Engine"),
        ("Final Progression")
    ]

    # adding progresion bar and desc is decription
    with tqdm (total = len(stages), desc = "Cad Assist in Progress", bar_format = bar_format) as progress_bar:
        # initialising the progresion bar and stages
        for name in stages:
            progress_bar.set_postfix_str(f"Stage:{name}")

            # simulate work progression (slow things so human can see the progression bar)
            time.sleep(0.5)

            # update the progression
            progress_bar.update(1)

    try:
        # we try to run and capture the outcome of this
        result = subprocess.run (
            [free_cad_cmd, str(script_path_use)],
            capture_output= True,
            text = True,
            timeout = 20
        )

        # if script finished without error it prints sucess 
        if result.returncode == 0 and not result.stderr.strip():
            print(f"Script Sucessfully Executed \n Script:{script_name}")
            print("Log:\n",result.stdout) # this prints what script printed
        else:
            # if failed we notify and store info in logs
            print(f"Failed \nCrash Script:{script_name}")


            # we have to create (if not exists) and write error report
            with open (log_report,"a") as file:
                file.write(result.stderr)

            print(f"Error Details Are Stored in ", {log_report})
    except subprocess.TimeoutExpired:
        # this part gonna catch the time breaker even
        print(f"Time Exceeded! Script took too long to run Perphaps Long infinte loop? \nUsed Script:{script_name}")
        # entering error in log 
        with open(log_report,"a") as file:
            file.write("Error: Execution Time Exceeded")
        print(f"Time_Out Details Stored in:{log_report}")

    
# 4. test run of runner.py
if __name__ == "__main__":
    # test the script 
    execute_cad_scripts("ai_gen_script.py")
    